import { serverClient } from "./_trpc/serverClient";
import GetLocationButton from "@components/GetLocationButton";
import Login from "@components/Login"
import { Metadata } from "next";
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function Home() {
  // const todos = await serverClient.getTodos();
  return (
    <main className=" mx-10 mt-5">
      <h1 className=" flex justify-center text-4xl">
        Welcome to  
        <span className="text-4xl text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-green-500">
           Electric Rescue
        </span>
      </h1>
      <div className="flex justify-center p-8">
        <button className="btn">Responsive</button>
      </div>
      <GetLocationButton />
      <Login/>
    </main>
  );
}
