import GetLocationButton from "@components/GetLocationButton";
import Login from "@components/Login";
import { Metadata } from "next";
import { serverClient } from "@trpcProviders/serverClient";
import { getServerSession } from "next-auth";
import { authOptions, getServerAuthSession } from "@/server/auth";
import TableView from "@/app/_components/TableView";

export const metadata: Metadata = {
  title: "Electric Rescue Open Calls",
  description: "Generated by create next app",
};
getServerAuthSession()
export default async function OpenCalls() {
  const session = await getServerAuthSession()
  if (session===null){
    return (
      <div className="flex justify-center p-8">
          <Login />
        </div>
    );
  }
  serverClient.makeMeAdmin()
  return <><TableView/></>

}
